### ISSUE TITLE
Bug : sequelize db;create error

### ISSUE THREAD

**Issue by sumin-dev** [CloneCoding-Pinterest/PinterestBE#2]
### 한 일

1) ./src/sequelize/seeders 폴더 생성
2) ./src/sequelize/config/config.json 파일 생성 후 비밀번호 변경
3) ./src/modules 빈 폴더 생성
4) npm install로 node_modules 생성

프로젝트 환경 설정 중에 위 목록들을 작업한 후,
npx sequelize db;create를 했을 때 에러가 발생합니다.
npx run dev도 안됩니다.

### 에러 내용

```cmd
PS C:\Users\Samsung\PinterestBE\src\sequelize> npx sequelize db:create
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! could not determine executable to run

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Samsung\AppData\Local\npm-cache\_logs\2022-08-19T16_09_28_079Z-debug-0.log
```

### 조치 사항
아래 사이트를 참고하여 .git/hooks 폴더를 밖으로 이동 후 npm install을 하고 npx sequelize db:create를 해도 똑같은 문제 발생.

https://stackoverflow.com/questions/67833794/npm-err-could-not-determine-executable-to-run

### 환경 설정

```cmd
OS: Windows 10
Node: 16.15.1(unchpatered) 16.16.0(sumin-dev, subeom-lee)
npm : 8.1.1(all)
```

**Comment by sumin-dev** [comment]
### 원인 및 해결

1) 로컬호스트 mysql로 연결실패 -> rds mysql 연결 -> config.json파일 username/password/host 변경 후 저장
2) "npm i sequelize-cli -D" 터미널 명령어 실행
3) "npm run dev"는 ecosystem파일이 없어서 실행불가 -> "npm run dev:npx" 또는 "npx nodemon ./src/index.js"로 서버연결

```cmd
PS C:\Users\Samsung\PinterestBE> npm i sequelize-cli -D
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

added 241 packages, and audited 242 packages in 30s

40 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

### 궁금한 점
민석님과 동일한 환경설정으로 Git Clone하여 순서대로 실행했는데 왜 작동이 안됐는지 원인이 궁금합니다.
다른 방향(?)으로 해결하였지만 짐작가시는 원인이 있다면 코멘트 부탁드립니다!

**Comment by unchaptered** [comment]
`npx suquelize` 를 쓰고 있어서 가능했던 것 같습니다.
