### ISSUE TITLE
Bug : Git commit error

### ISSUE THREAD

**Issue by subeom-lee** [CloneCoding-Pinterest/PinterestBE#6]
### 한 일

git add .
git commit -m "sequelize model을 받기위한 임시저장"

### 에러 내용

```cmd
git commit -m "sequelize model을 받기위한 임시저장"
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
'"node"'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.
husky - pre-commit hook exited with code 1 (error)
```

### 조치 사항

npm run prepare 을 통해 husky install 을 진행했음 에도 해당 에러가 해결 되지 않아서
git commit -m "sequelize model을 받기위한 임시저장"--no-verify
이렇게 뒤에 --no-verify을 붙혀서 저장해줬다.

### 환경 설정

```cmd
OS: window10
Node: 16.15.1(unchpatered) 16.16.0(sumin-dev, subeom-lee)
npm : 8.1.1(all)
```

**Comment by unchaptered** [comment]
`npm run prepare` 을 통해서 `husky install`
